//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootyStreet.Data
{
    
    
    
    using System;
    using System.Collections.Generic;
    using Framework.Entities;
    using System.Linq;
    public partial class Color : IInsertTracker, IUpdateTracker
    {
        public Color()
        {
            this.ProductUOMColors = new HashSet<ProductUOMColor>();
        }
    
        public int ColorID { get; set; }
        public string ColorHexCode { get; set; }
        public string ColorRGBCode { get; set; }
        public string ColorName { get; set; }
        public string ColorDescription { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<ProductUOMColor> ProductUOMColors { get; set; }
    
    }
}
