//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootyStreet.Data
{
    
    
    
    using System;
    using System.Collections.Generic;
    using Framework.Entities;
    using System.Linq;
    public partial class Contact : IInsertTracker, IUpdateTracker
    {
        public int ContactID { get; set; }
        public string PrimaryPhoneNumber { get; set; }
        public string AlternatePhoneNumber { get; set; }
        public string Email { get; set; }
        public string AlternateEmail { get; set; }
        public string Fax { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
    }
}
