//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootyStreet.Data
{
    
    
    
    using System;
    using System.Collections.Generic;
    using Framework.Entities;
    using System.Linq;
    public partial class Offer : IInsertTracker, IUpdateTracker
    {
        public Offer()
        {
            this.ProductOffers = new HashSet<ProductOffer>();
        }
    
        public int OfferID { get; set; }
        public string OfferTitle { get; set; }
        public string OfferDescription { get; set; }
        public string OfferFinePrint { get; set; }
        public decimal OfferDiscountPercentage { get; set; }
        public System.DateTime OfferBeginDate { get; set; }
        public Nullable<System.DateTime> OfferEndDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<ProductOffer> ProductOffers { get; set; }
    
    }
}
