//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootyStreet.Data
{
    
    
    
    using System;
    using System.Collections.Generic;
    using Framework.Entities;
    using System.Linq;
    public partial class OrderHeader : IInsertTracker, IUpdateTracker
    {
        public OrderHeader()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int OrderHeaderID { get; set; }
        public string OrderNumber { get; set; }
        public int PersonID { get; set; }
        public string ShippingAddressID { get; set; }
        public int ShippingDetailID { get; set; }
        public bool OrderDate { get; set; }
        public System.DateTime ExpectedShippingDate { get; set; }
        public int PaymentModeID { get; set; }
        public decimal TotalDue { get; set; }
        public int OrderStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ShippingDetail ShippingDetail { get; set; }
    
    }
}
