//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootyStreet.Data
{
    
    
    
    using System;
    using System.Collections.Generic;
    using Framework.Entities;
    using System.Linq;
    public partial class ProductDetail : IInsertTracker, IUpdateTracker
    {
        public ProductDetail()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ProductDetailID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductMake { get; set; }
        public int ProductVendorID { get; set; }
        public int PriceID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Price Price { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual Vendor Vendor { get; set; }
    
    }
}
