//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootyStreet.Data
{
    
    
    
    using System;
    using System.Collections.Generic;
    using Framework.Entities;
    using System.Linq;
    public partial class Product : IInsertTracker, IUpdateTracker
    {
        public Product()
        {
            this.ProductCategorySubCategories = new HashSet<ProductCategorySubCategory>();
            this.ProductOffers = new HashSet<ProductOffer>();
            this.ProductReviews = new HashSet<ProductReview>();
            this.ProductUOMColors = new HashSet<ProductUOMColor>();
            this.ProductTags = new HashSet<ProductTag>();
            this.ProductImages = new HashSet<ProductImage>();
        }
    
        public int ProductID { get; set; }
        public string ProductNumber { get; set; }
        public int ProductDetailID { get; set; }
        public System.DateTime ProductBeginDate { get; set; }
        public Nullable<System.DateTime> ProductDiscontinuedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<ProductCategorySubCategory> ProductCategorySubCategories { get; set; }
        public virtual ICollection<ProductOffer> ProductOffers { get; set; }
        public virtual ICollection<ProductReview> ProductReviews { get; set; }
        public virtual ICollection<ProductUOMColor> ProductUOMColors { get; set; }
        public virtual ICollection<ProductTag> ProductTags { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
    
    }
}
