//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootyStreet.Data
{
    
    
    
    using System;
    using System.Collections.Generic;
    using Framework.Entities;
    using System.Linq;
    public partial class ProductPrice : IInsertTracker, IUpdateTracker
    {
        public int ProductPriceID { get; set; }
        public int ProductUOMColorID { get; set; }
        public int ProductBasePrice { get; set; }
        public decimal ProductMarginPrice { get; set; }
        public decimal ProductListPrice { get; set; }
        public decimal Taxes { get; set; }
        public Nullable<decimal> OtherCosts { get; set; }
        public decimal ProductSellingPrice { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ProductUOMColor ProductUOMColor { get; set; }
    
    }
}
