//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootyStreet.Data
{
    
    
    
    using System;
    using System.Collections.Generic;
    using Framework.Entities;
    using System.Linq;
    public partial class ProductUOMColor : IInsertTracker, IUpdateTracker
    {
        public ProductUOMColor()
        {
            this.Invoices = new HashSet<Invoice>();
            this.ProductInventories = new HashSet<ProductInventory>();
            this.ProductPrices = new HashSet<ProductPrice>();
        }
    
        public int ProductUOMColorID { get; set; }
        public int ProductID { get; set; }
        public int UOMID { get; set; }
        public int ColorID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<ProductInventory> ProductInventories { get; set; }
        public virtual ICollection<ProductPrice> ProductPrices { get; set; }
        public virtual UnitofMeasure UnitofMeasure { get; set; }
    
    }
}
