//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootyStreet.Data
{
    
    
    
    using System;
    using System.Collections.Generic;
    using Framework.Entities;
    using System.Linq;
    public partial class ShippingDetail : IInsertTracker, IUpdateTracker
    {
        public ShippingDetail()
        {
            this.OrderHeaders = new HashSet<OrderHeader>();
        }
    
        public int ShippingDetailID { get; set; }
        public string ShippingMode { get; set; }
        public string ShippingModeDescription { get; set; }
        public decimal ShippingRate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<OrderHeader> OrderHeaders { get; set; }
    
    }
}
