//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootyStreet.Data
{
    
    
    
    using System;
    using System.Collections.Generic;
    using Framework.Entities;
    using System.Linq;
    public partial class Tag : IInsertTracker, IUpdateTracker
    {
        public Tag()
        {
            this.ProductTags = new HashSet<ProductTag>();
        }
    
        public int TagID { get; set; }
        public string TagName { get; set; }
        public string TagDescription { get; set; }
        public int CategoryID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<ProductTag> ProductTags { get; set; }
    
    }
}
