//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootyStreet.Data
{
    
    
    
    using System;
    using System.Collections.Generic;
    using Framework.Entities;
    using System.Linq;
    public partial class UnitofMeasure : IInsertTracker, IUpdateTracker
    {
        public UnitofMeasure()
        {
            this.ProductUOMColors = new HashSet<ProductUOMColor>();
        }
    
        public int UOMID { get; set; }
        public string UOMDescription { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string UOMShortCode { get; set; }
    
        public virtual ICollection<ProductUOMColor> ProductUOMColors { get; set; }
    
    }
}
