//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootyStreet.Data
{
    
    
    
    using System;
    using System.Collections.Generic;
    using Framework.Entities;
    using System.Linq;
    public partial class Vendor : IInsertTracker, IUpdateTracker
    {
        public Vendor()
        {
            this.ProductDetails = new HashSet<ProductDetail>();
        }
    
        public int VendorID { get; set; }
        public string VendorName { get; set; }
        public int AddressID { get; set; }
        public int ContactID { get; set; }
        public string VendorDescription { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
    
    }
}
